export const GAME_LIMITS = {
  MIN_PLAYERS: 2,
  MAX_PLAYERS: 6,
  MIN_ROUNDS: 3,
  MAX_ROUNDS: 10,
  DEFAULT_ROUNDS: 5,
  MIN_TIMER: 15,
  MAX_TIMER: 60,
  DEFAULT_TIMER: 30,
  WHITE_DICE_COUNT: 9,
  HIDDEN_DICE_COUNT: 2,
  DICE_PER_SELECTION: 3,
  ROOM_CODE_LENGTH: 6,
  RECONNECT_GRACE_PERIOD_MS: 30000,
  REVEAL_DELAY_MS: 3000,
  ROUND_SUMMARY_DELAY_MS: 5000,
  ROOM_EXPIRY_MS: 3600000, // 1 hour
} as const;

export const DEFAULT_GAME_CONFIG = {
  maxPlayers: GAME_LIMITS.MAX_PLAYERS,
  totalRounds: GAME_LIMITS.DEFAULT_ROUNDS,
  turnTimerSeconds: GAME_LIMITS.DEFAULT_TIMER,
} as const;

export type GameLimits = typeof GAME_LIMITS;
